version: '3.8'

services:
  host:
    build:
      context: .
      dockerfile: apps/host/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REMOTE_URL=http://remote:3001
      - BFF_URL=http://bff:3002
    depends_on:
      - remote
      - bff
    networks:
      - micro-frontend

  remote:
    build:
      context: .
      dockerfile: apps/remote/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - micro-frontend

  bff:
    build:
      context: .
      dockerfile: apps/bff/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    networks:
      - micro-frontend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - host
      - remote
      - bff
    networks:
      - micro-frontend

networks:
  micro-frontend:
    driver: bridge